### ISSUE TITLE
Add certificate expiration date

### ISSUE THREAD

**Issue by zerkms** [anas-aso/ssllabs_exporter#16]
It's available in ssllabs response, how about exposing it as well, so that one could trigger an alert if a certificate for some reason hasn't been renewed.

**Comment by anas-aso** [comment]
[BlackBox Exporter](https://github.com/prometheus/blackbox_exporter) already provides this feature. You can check https://www.robustperception.io/get-alerted-before-your-ssl-certificates-expire as an example.
