### ISSUE TITLE
Implement using `fromCache`

### ISSUE THREAD

**Issue by zerkms** [anas-aso/ssllabs_exporter#18]
I believe in current implementation

```go
	if new {
		request += "&startNew=on"
	}
```
is not necessary. Alternatively I think it would benefit if `fromCache` + `maxAge` were used instead: with `maxAge` set to the same value as cache duration. In such a case if you redeploy the application and it recently requested the ssllabs report - it would happily be served from the ssllabs api cache.

I created quite a few reports today. I will be developing them for myself in any way, but it would be helpful if we agreed on some common ground implementation so that a different (my) fork existed for too long.

Thanks! :-)

**Comment by anas-aso** [comment]
@zerkms I think your suggestion makes sense. Please feel free to open a PR for it and I will be happy to review it.

**Comment by zerkms** [comment]
To be honest - after running this project for a couple days I realised it's too many extra features I need in particular for my infrastructure, so that for me it was easier to implement another one (not opensource unfortunately) using the https://github.com/essentialkaos/sslscan client.
