### ISSUE TITLE
Cache efficiency

### ISSUE THREAD

**Issue by zerkms** [anas-aso/ssllabs_exporter#19]
I suspect that for cache size below at least 1000 entries (which is extremely high for this exporter) just having a map without a linked list would be quicker and consume less memory.

Does it make sense to have benchmark that verifies if the current solution worth having it (and extra complexity it carries)?

**Comment by anas-aso** [comment]
Since the current solution doesn't introduce issues and would work for larger setups, I don't see a reason for changing it.
Regarding the benchmark, feel free to open a PR for them and I will be happy to review it.
