### ISSUE TITLE
Expose grade as number

### ISSUE THREAD

**Issue by omerlh** [anas-aso/ssllabs_exporter#2]
Use SSL lab grade guide and translate the grade to number instead of checking only for A. This allows more flexibility for users to choose the required minimum grade for their service.

**Comment by anas-aso** [comment]
I have a change for that in a local branch that I need to finish, but if you want to take over PRs are welcome.

**Comment by omerlh** [comment]
This is still not good enough - I want an alert if the grade go bellow a specific grade, e.g. B. .I would expect to get the grade as number so I could do that - does that makes sense?
