### ISSUE TITLE
Add support for caching

### ISSUE THREAD

**Issue by omerlh** [anas-aso/ssllabs_exporter#3]
SSL labs limits the number of assessments you can run. To avoid hitting this limits, we can use SSL labs results cache instead of running a new analysis. Suggested to add a new configuration - cache duration - and pass it to SSL labs.

**Comment by anas-aso** [comment]
@omerlh right now the exporter returns cached results as long as they are within the configurable timeout. I think this should be enough to answer your need, or?

**Comment by omerlh** [comment]
Yes, thank you!

**Comment by anas-aso** [comment]
@omerlh I have an open PR for this in case you are interested in reviewing it.
